language: ruby
bundler_args: "--without development:production"
cache: bundler
sudo: false
script:
- bundle exec rake
- bundle exec rubocop --rails
rvm:
- 2.2.0
env:
  global:
  - OHANA_API_ENDPOINT=http://api.smc-connect.org
